Update README.md
CodandoApple/aprenda-swift pull request #26
Opened 2023-04-26 19:02 UTC by alexandresantosal91

Adicionei as trilhas do Paul Hudson sobre 100 Days of Swift e 100 Days of SwiftUI.

2023-04-26 21:18 UTC, reisdev commented
Os links adicionados já existem na lista, na seção de "Tutoriais". Acho que seria interessante movê-los para a categoria "Cursos" e remover os da seção "Tutoriais" para não haver redundância.

2023-04-26 21:21 UTC, reisdev requested changes
Remover os itens da seção "Tutoriais" que já continham os links adicionados.

2023-04-26 21:23 UTC, alexandresantosal91 commented
Ok, sem problemas...

2023-04-26 21:25 UTC, alexandresantosal91 commented
Obrigado, da próxima vez irei tentar ser mais atento a esses pequenos detalhes.

2023-05-03 19:38 UTC, Rychillie approved these changes

2023-05-12 17:42 UTC, reisdev approved these changes

2023-05-12 17:42 UTC, merged